/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloHaskell */

#ifndef _Included_HelloHaskell
#define _Included_HelloHaskell
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloHaskell
 * Method:    fibonacci
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_HelloHaskell_fibonacci
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
